"""Set CarBrand OriginCountry NotNull

Revision ID: 2cda03b4a893
Revises: 3db881578db3
Create Date: 2025-12-21 19:55:23.804703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cda03b4a893'
down_revision = '3db881578db3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car_brand', schema=None) as batch_op:
        batch_op.alter_column('OriginCountry',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car_brand', schema=None) as batch_op:
        batch_op.alter_column('OriginCountry',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)

    # ### end Alembic commands ###
