"""Add OriginCountry to CarBrand

Revision ID: 3db881578db3
Revises: a28b2eac04e9
Create Date: 2025-12-21 19:50:42.739918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3db881578db3'
down_revision = 'a28b2eac04e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car_brand', schema=None) as batch_op:
        batch_op.add_column(sa.Column('OriginCountry', sa.String(length=80), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car_brand', schema=None) as batch_op:
        batch_op.drop_column('OriginCountry')

    # ### end Alembic commands ###
