"""Add Year column to CardModel

Revision ID: a28b2eac04e9
Revises: 
Create Date: 2025-12-21 19:46:56.770935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a28b2eac04e9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car_model', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Year', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car_model', schema=None) as batch_op:
        batch_op.drop_column('Year')

    # ### end Alembic commands ###
