"""Add GameDeveloper.Country

Revision ID: c3c6868e3a87
Revises: 
Create Date: 2025-12-22 19:20:19.454384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3c6868e3a87'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('developer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('country', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('developer', schema=None) as batch_op:
        batch_op.drop_column('country')

    # ### end Alembic commands ###
